version: "3"

services:
  app:
    build:
      context: ./app
    container_name: my-node-app
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
